package cn.zhangpeng.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2019-08-12T14:58:53.405+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://servcie.cxf.webservice.zhangpeng.cn/", name = "WeatherService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WeatherService {

    @WebMethod
    @WebResult(name = "getWeather", targetNamespace = "http://servcie.cxf.webservice.zhangpeng.cn/", partName = "getWeather")
    public String getWeatherMethod(
            @WebParam(partName = "cityName", name = "cityName")
                    String cityName
    );
}
